# Generated by Django 3.2.4 on 2021-07-07 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20210708_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_src', models.TextField(max_length=200)),
                ('port_src', models.TextField(max_length=200)),
                ('ip_des', models.TextField(max_length=200)),
                ('port_des', models.TextField(max_length=200)),
                ('classification', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 1, 37, 5, 872621)),
        ),
    ]
