# Generated by Django 3.2.4 on 2021-07-07 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20210708_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 1, 37, 11, 918629)),
        ),
    ]
