# Generated by Django 3.2.4 on 2021-07-07 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_alter_files_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 1, 38, 7, 749599)),
        ),
        migrations.AlterField(
            model_name='resultml',
            name='classification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultml',
            name='ip_des',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultml',
            name='ip_src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultml',
            name='port_des',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultml',
            name='port_src',
            field=models.CharField(max_length=200),
        ),
    ]
